all: task1 task2 task3 task4 task5

task1: task1.c
	gcc $^ -lcrypto -o $@

task2: task2.c
	gcc $^ -lcrypto -o $@

task3: task3.c
	gcc $^ -lcrypto -o $@

task4: task4.c
	gcc $^ -lcrypto -o $@

task5: task5.c
	gcc $^ -lcrypto -o $@

clean:
	rm -f *.o *.out *~
	rm task1 task2 task3 task4 task5
